services:
  - type: web
    name: whatsapp-backend
    env: node
    buildCommand: |
      npm install
      npx @puppeteer/browsers install chrome@stable
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-*/chrome-linux*/chrome
